export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Link from "next/link";

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <nav>

      </nav>
      <body>{children}</body>
    </html>
  )
}
